name: Deploy-wagtail

# глобальные переменные будут видны везде - в любых моих джобах
env: 
  APPLICATION_NAME    : "myWagtailApp"
  SHA_COMMIT          : "deploy version - ${{github.sha}}" 
  DEPLOY_PACKAGE_NAME : "wagtail_app_${{ github.sha }}"
on:
  push:
    branches: 
    - main

jobs:
  my-testing:
  
    # запускаем на ubuntu
    runs-on: ubuntu-latest
    
    # команды
    steps:
        # название команды
      - name: Print my testing
        # сама команда
        run: echo "Hello test 1"
      - name: Versions commit
      # с помощью | запускаю несколько команд
        run: | 
          echo "commands 1"
          echo "commands 2"
          echo "name: ${{ env.APPLICATION_NAME }}"

  
  my-testing-2:
    # запускаем на ubuntu
    runs-on: ubuntu-latest
    needs: [my-testing] #этот джоб (my-testing-2) запустится только после того как отработает my-testing - первый джоб 
    
    # команды
    steps:
        # название команды
      - name: Print my testing 2 after needs
        # сама команда
        run: echo "Hello test 2"
      - name: Geting commit number
        run: | 
          echo "commit  number: ${{ env.SHA_COMMIT }}"
          
  linux-comands:
    runs-on: ubuntu-latest
    needs: [my-testing-2]
    
    steps:
      - name: Git clone
        uses:  actions/checkout@v1
        
      - name: Зипуем репозиторий для Deploy
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
        
           
