name: Deploy-wagtail

on:
  push:
    branches: 
    - main

jobs:
  my-testing:
  
    # запускаем на ubuntu
    runs-on: ubuntu-latest
    
    # команды
    steps:
        # название команды
      - name: Print my testing
        # сама команда
        run: echo "Hello test 1"
        
  my-testing-2:
    # запускаем на ubuntu
    runs-on: ubuntu-latest
    needs: [my-testing] #этот джоб my-testing-2 запустится только после того как отработает my-testing - первый джоб 
    
    # команды
    steps:
        # название команды
      - name: Print my testing 2 after needs
        # сама команда
        run: echo "Hello test 2"        
