name: Deploy-wagtail

on:
  push:
    branches: 
    - master

jobs:
  my-testing:
  
    # запускаем на ubuntu
    runs-on: ubuntu-latest
    
    # команды
    steps:
        # название команды
      - name: Print my testing
        # сама команда
        run: echo "Hello test 1"
        
  my-testing-2:
    # запускаем на ubuntu
    runs-on: ubuntu-latest
    
    # команды
    steps:
        # название команды
      - name: Print my testing 2
        # сама команда
        run: echo "Hello test 2"        
